name: pokedex
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  dio: ^5.5.0+1
  get_it: ^7.7.0
  skeletonizer: ^1.3.0
  shared_preferences: ^2.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
